#ifndef _REVOLUTION_HBM_NW4HBM_SND_HPP
#define _REVOLUTION_HBM_NW4HBM_SND_HPP

#include "revolution/hbm/nw4hbm/snd/AxManager.h"
#include "revolution/hbm/nw4hbm/snd/AxVoice.h"
#include "revolution/hbm/nw4hbm/snd/Bank.h"
#include "revolution/hbm/nw4hbm/snd/BankFile.h"
#include "revolution/hbm/nw4hbm/snd/BasicPlayer.h"
#include "revolution/hbm/nw4hbm/snd/BasicSound.h"
#include "revolution/hbm/nw4hbm/snd/Channel.h"
#include "revolution/hbm/nw4hbm/snd/ChannelManager.h"
#include "revolution/hbm/nw4hbm/snd/DisposeCallback.h"
#include "revolution/hbm/nw4hbm/snd/DisposeCallbackManager.h"
#include "revolution/hbm/nw4hbm/snd/DvdSoundArchive.h"
#include "revolution/hbm/nw4hbm/snd/ExternalSoundPlayer.h"
#include "revolution/hbm/nw4hbm/snd/FrameHeap.h"
#include "revolution/hbm/nw4hbm/snd/FxBase.h"
#include "revolution/hbm/nw4hbm/snd/InstanceManager.h"
#include "revolution/hbm/nw4hbm/snd/InstancePool.h"
#include "revolution/hbm/nw4hbm/snd/Lfo.h"
#include "revolution/hbm/nw4hbm/snd/MemorySoundArchive.h"
#include "revolution/hbm/nw4hbm/snd/MidiSeqPlayer.h"
#include "revolution/hbm/nw4hbm/snd/MidiSeqTrack.h"
#include "revolution/hbm/nw4hbm/snd/MmlParser.h"
#include "revolution/hbm/nw4hbm/snd/MmlSeqTrack.h"
#include "revolution/hbm/nw4hbm/snd/MmlSeqTrackAllocator.h"
#include "revolution/hbm/nw4hbm/snd/NandSoundArchive.h"
#include "revolution/hbm/nw4hbm/snd/NoteOnCallback.h"
#include "revolution/hbm/nw4hbm/snd/PlayerHeap.h"
#include "revolution/hbm/nw4hbm/snd/RemoteSpeaker.h"
#include "revolution/hbm/nw4hbm/snd/RemoteSpeakerManager.h"
#include "revolution/hbm/nw4hbm/snd/SeqFile.h"
#include "revolution/hbm/nw4hbm/snd/SeqPlayer.h"
#include "revolution/hbm/nw4hbm/snd/SeqSound.h"
#include "revolution/hbm/nw4hbm/snd/SeqSoundHandle.h"
#include "revolution/hbm/nw4hbm/snd/SeqTrack.h"
#include "revolution/hbm/nw4hbm/snd/SeqTrackAllocator.h"
#include "revolution/hbm/nw4hbm/snd/SoundArchive.h"
#include "revolution/hbm/nw4hbm/snd/SoundArchiveFile.h"
#include "revolution/hbm/nw4hbm/snd/SoundArchiveLoader.h"
#include "revolution/hbm/nw4hbm/snd/SoundArchivePlayer.h"
#include "revolution/hbm/nw4hbm/snd/SoundHandle.h"
#include "revolution/hbm/nw4hbm/snd/SoundHeap.h"
#include "revolution/hbm/nw4hbm/snd/SoundInstanceManager.h"
#include "revolution/hbm/nw4hbm/snd/SoundPlayer.h"
#include "revolution/hbm/nw4hbm/snd/SoundStartable.h"
#include "revolution/hbm/nw4hbm/snd/SoundThread.h"
#include "revolution/hbm/nw4hbm/snd/StrmFile.h"
#include "revolution/hbm/nw4hbm/snd/StrmPlayer.h"
#include "revolution/hbm/nw4hbm/snd/StrmSound.h"
#include "revolution/hbm/nw4hbm/snd/Task.h"
#include "revolution/hbm/nw4hbm/snd/TaskManager.h"
#include "revolution/hbm/nw4hbm/snd/TaskThread.h"
#include "revolution/hbm/nw4hbm/snd/Util.h"
#include "revolution/hbm/nw4hbm/snd/WaveFile.h"
#include "revolution/hbm/nw4hbm/snd/WavePlayer.h"
#include "revolution/hbm/nw4hbm/snd/WaveSound.h"
#include "revolution/hbm/nw4hbm/snd/WsdFile.h"
#include "revolution/hbm/nw4hbm/snd/WsdPlayer.h"
#include "revolution/hbm/nw4hbm/snd/WsdTrack.h"
#include "revolution/hbm/nw4hbm/snd/debug.h"
#include "revolution/hbm/nw4hbm/snd/global.h"
#include "revolution/hbm/nw4hbm/snd/mix.h"
// #include "revolution/hbm/nw4hbm/snd/snd_AxVoiceManager.hpp"
// #include "revolution/hbm/nw4hbm/snd/snd_EnvGenerator.hpp"
// #include "revolution/hbm/nw4hbm/snd/snd_MoveValue.hpp"
// #include "revolution/hbm/nw4hbm/snd/snd_SoundActor.hpp"
// #include "revolution/hbm/nw4hbm/snd/snd_SoundMemoryAllocatable.hpp"
// #include "revolution/hbm/nw4hbm/snd/SoundSystem.h"
// #include "revolution/hbm/nw4hbm/snd/snd_StrmChannel.hpp"
// #include "revolution/hbm/nw4hbm/snd/snd_StrmSoundHandle.hpp"
// #include "revolution/hbm/nw4hbm/snd/snd_Types.hpp"
// #include "revolution/hbm/nw4hbm/snd/snd_Voice.hpp"
// #include "revolution/hbm/nw4hbm/snd/snd_VoiceManager.hpp"
// #include "revolution/hbm/nw4hbm/snd/snd_WaveArchive.hpp"
// #include "revolution/hbm/nw4hbm/snd/snd_WaveSoundHandle.hpp"
// #include "revolution/hbm/nw4hbm/snd/snd_adpcm.hpp"

#endif
